
export const ADD_MEDICINE_NAME = 'ADD_MEDICINE_NAME';
export const FETCH_MEDICINE_NAME = 'FETCH_MEDICINE_NAME';
export const UPDATE_MEDICINE_NAME = 'UPDATE_MEDICINE_NAME';
export const EDIT_MEDICINE_NAME = 'EDIT_MEDICINE_NAME';
export const REMOVE_MEDICINE_NAME = 'REMOVE_MEDICINE_NAME';

export const ADD_MEDICINE_CATEGORY = 'ADD_MEDICINE_CATEGORY';
export const FETCH_MEDICINE_CATEGORY = 'FETCH_MEDICINE_CATEGORY';
export const UPDATE_MEDICINE_CATEGORY = 'UPDATE_MEDICINE_CATEGORY';
export const EDIT_MEDICINE_CATEGORY = 'EDIT_MEDICINE_CATEGORY';
export const REMOVE_MEDICINE_CATEGORY = 'REMOVE_MEDICINE_CATEGORY';

export const ADD_MEDICINE = 'ADD_MEDICINE';
export const FETCH_MEDICINE = 'FETCH_MEDICINE';
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE';
export const REMOVE_MEDICINE = 'REMOVE_MEDICINE';

export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING_MEDICINE = 'SET_LOADING_MEDICINE';
export const SET_LOADING_NAME = 'SET_LOADING_NAME';
export const SET_LOADING_CATEGORY = 'SET_LOADING_CATEGORY';